### ISSUE TITLE
Few Tweaks for Error Handling

### ISSUE THREAD

**Issue by securityinfive** [alxhslm/journey2dayone#2]
This is a fantastic script! I did find a few hiccups and my Journey entries are diverse and came across a few things to improve around data error handling. 

I am a coder but not into GitHub branches/commits. Plus my tweaks are a few lines you can add easily. 

**First -** 
  Sometimes an entry may not have a Timezone and if timezone is " " it will fail. 
I added this below to 'default' to my current timezone to fill in the gap. 

 All in the following function. 

def journeyjson2dayonejson(journey):
    if journey["timezone"] == "":
        timez = "America/Chicago"
    else:
        timez = journey["timezone"]

    vvv Modified this line to use the timez var vvv
   "creationDate": convert_unixtime(journey["date_journal"], timez),

**Second**
I found that when I created an entry with iOS voice to text, not sure if that's the reason, I was getting _'charmap' codec can't decode byte 0x9d]_ errors. 

I added on the "open to ignore" errors and it works just fine, I have put hundreds of entries through it. It's not ideal, the violating character  , a ' in my case, is converted to a goofy character but is easily manually fixed if needed after DayOne Import. 

for f in glob.glob("./journey/*.json"):
    with open(f, "r", _errors='ignore'_) as fh:

**Comment by alxhslm** [comment]
Thanks for using the script - I'm glad it was useful!

> Sometimes an entry may not have a Timezone and if timezone is " " it will fail.

It's difficult for me to identify all of these edge cases, so thanks for telling me about this. I've updated the script to default to the local timezone as suggested.

> I found that when I created an entry with iOS voice to text, not sure if that's the reason, I was getting 'charmap' codec can't decode byte 0x9d] errors.

If you have a example entry you're happy to share, I can take a look to see if I can identify the problem.
